version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mcp-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mcpuser
      - MONGO_INITDB_ROOT_PASSWORD=mcppassword
    volumes:
      - mongodb_data:/data/db
    networks:
      - mcp-network

  # Optional: MongoDB client (Mongo Express)
  mongo-express:
    image: mongo-express
    container_name: mcp-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mcpuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mcppassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  mongodb_data: